### ISSUE TITLE
可视化的实现

### ISSUE THREAD

**Issue by sun133233** [yimeng-fan/SFOD#1]
请问一下，在README当中的可视化是如何实现的？

**Comment by yimeng-fan** [comment]
您好，可视化是自己写的积分程序，具体地，可以将测试时给模型推理的事件流进行积分，并将检测框画在图中

---- 回复的原邮件 ----
发件人 ***@***.***> 发送日期 2024年4月15日 09:48 收件人 ***@***.***> 抄送人 ***@***.***> 主题 [yimeng-fan/SFOD] 可视化的实现 (Issue #1)  
请问一下，在README当中的可视化是如何实现的？

**Comment by sun133233** [comment]
> 您好，可视化是自己写的积分程序，具体地，可以将测试时给模型推理的事件流进行积分，并将检测框画在图中
> […](#)
> ---- 回复的原邮件 ---- 发件人 ***@***.***> 发送日期 2024年4月15日 09:48 收件人 ***@***.***> 抄送人 ***@***.***> 主题 [yimeng-fan/SFOD] 可视化的实现 (Issue #1) 请问一下，在README当中的可视化是如何实现的？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

好的，谢谢！
